name: Runner 🤲

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        required: true
        description: "Action to perform"
        options:
          - clockin
          - clockout
  workflow_call:
    inputs:
      action:
        type: string
        required: true

concurrency:
  group: runner
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    environment: talentless
    steps:
      - name: Checkout code 📁
        uses: actions/checkout@v4

      - name: Setup NodeJS 💻
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "yarn"

      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile

      - name: Debug env vars 🐞
        run: |
          echo "EMAIL: $TALENTLESS_EMAIL"
          echo "CAL: $TALENTLESS_PERSONAL_CALENDAR_LINK"
        env:
          TALENTLESS_EMAIL: ${{ secrets.TALENTLESS_EMAIL }}
          TALENTLESS_PERSONAL_CALENDAR_LINK: ${{ secrets.TALENTLESS_PERSONAL_CALENDAR_LINK }}

      - name: Running action 💨
        run: node --no-warnings index.ts -p ${{ inputs.action }}
        env:
          HEADLESS: 1
          TALENTLESS_EMAIL: ${{ secrets.TALENTLESS_EMAIL }}
          TALENTLESS_PASSWORD: ${{ secrets.TALENTLESS_PASSWORD }}
          TALENTLESS_PERSONAL_CALENDAR_LINK: ${{ secrets.TALENTLESS_PERSONAL_CALENDAR_LINK }}
          TALENTLESS_LAT: "-6.168104328353934"
          TALENTLESS_LNG: "106.87375988135086"

      - name: Notify Errors 🚨
        if: ${{ failure() }}
        run: |
          curl -H "Title: Talentless Runner Failed: ${{ inputs.action }}" \
               -H "Priority: high" \
               -H "Tags: rotating_light,talentless" \
               -d "The runner workflow has failed: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n\nError: ${{ steps.*.outcome }}\n\nDetails: ${{ steps.*.conclusion }}" \
               https://ntfy.sh/${{ secrets.NTFY_TOPIC }}
